In [2]:
import torch
import numpy as np

In [27]:
def conv1D(x, w, p = 0, s = 1):
    w_rot = np.array(w[::-1])
    x_padded = np.array(x)
    if p > 0:
        padded_arr = np.zeros(p)
        x_padded = np.concatenate([padded_arr , x_padded , padded_arr])
    res = []
    for i in range(0, int(len(x_padded) - len(w_rot)) + 1, s):
        res.append(np.sum(x_padded[i:i + w_rot.shape[0]] * w_rot))
    return np.array(res)

In [28]:
x = [1, 3, 2, 4, 5, 6, 1, 3]

In [29]:
w = [1, 0, 3, 1, 2]

In [30]:
print('Conv1d Implementation:',
... conv1D(x, w, p=2, s=1))

Conv1d Implementation: [ 5. 14. 16. 26. 24. 34. 19. 22.]


In [31]:
print('NumPy Results:',
... np.convolve(x, w, mode='same'))

NumPy Results: [ 5 14 16 26 24 34 19 22]


In [32]:
import scipy.signal 

In [57]:
def conv2D(X,W, p =(0,0), s=(1,1)):
    W_rot = np.array(W)[::-1,::-1]
    X_org = np.array(X)
    n1 = X_org.shape[0]+ 2*p[0]
    n2 = X_org.shape[1]+ 2*p[1]
    X_padded = np.zeros((n1,n2))
    X_padded[p[0]:p[0]+X_org.shape[0], p[1] : p[1] +X_org.shape[1]] = X_org
    res = []
    for i in range(0, int((X_padded.shape[0] - W_rot.shape[0])/s[0]) + 1, s[0]):
        res.append([])
        for j in range(0, int((X_padded.shape[1] - W_rot.shape[1]) / s[1]) + 1, s[1]):
            X_sub = X_padded[i:i + W_rot.shape[0], j:j + W_rot.shape[1]]
            res[-1].append(np.sum(X_sub*W_rot))
    return np.array(res)

In [58]:
X = [[1, 3, 2, 4], [5, 6, 1, 3], [1, 2, 0, 2], [3, 4, 3, 2]]

In [59]:
W = [[1, 0, 3], [1, 2, 1], [0, 1, 1]]

In [60]:
print('Conv2d Implementation:\n',conv2D(X, W, p=(1, 1), s=(1, 1)))

Conv2d Implementation:
 [[11. 25. 32. 13.]
 [19. 25. 24. 13.]
 [13. 28. 25. 17.]
 [11. 17. 14.  9.]]


In [61]:
print('SciPy Results:\n',scipy.signal.convolve2d(X, W, mode='same'))

SciPy Results:
 [[11 25 32 13]
 [19 25 24 13]
 [13 28 25 17]
 [11 17 14  9]]
